const List<Map<String, dynamic>> placeSeedData = [
  {
    "id": 1,
    "name": "Eiffel Tower",
    "city": "Paris",
    "country": "France",
    "imageUrl": "https://images.unsplash.com/photo-1549144511-f099e773c147",
    "description":
        "Iconic iron tower and one of the most famous landmarks in the world.",
  },
  {
    "id": 2,
    "name": "Great Wall",
    "city": "Beijing",
    "country": "China",
    "imageUrl": "https://images.unsplash.com/photo-1508804185872-d7badad00f7d",
    "description":
        "Ancient series of walls and fortifications stretching across China.",
  },
  {
    "id": 3,
    "name": "Statue of Liberty",
    "city": "New York",
    "country": "USA",
    "imageUrl": "https://images.unsplash.com/photo-1467269204594-9661b134dd2b",
    "description": "Famous symbol of freedom located on Liberty Island.",
  },
  {
    "id": 4,
    "name": "Taj Mahal",
    "city": "Agra",
    "country": "India",
    "imageUrl": "https://images.unsplash.com/photo-1564507592333-c60657eea523",
    "description":
        "Magnificent white marble mausoleum and UNESCO World Heritage site.",
  },
  {
    "id": 5,
    "name": "Burj Khalifa",
    "city": "Dubai",
    "country": "UAE",
    "imageUrl": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    "description":
        "Tallest building in the world with breathtaking city views.",
  },
  {
    "id": 6,
    "name": "Santorini",
    "city": "Santorini",
    "country": "Greece",
    "imageUrl": "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff",
    "description": "Beautiful island known for white buildings and blue domes.",
  },
  {
    "id": 7,
    "name": "Colosseum",
    "city": "Rome",
    "country": "Italy",
    "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    "description": "Ancient Roman amphitheater and major tourist attraction.",
  },
  {
    "id": 8,
    "name": "Machu Picchu",
    "city": "Cusco",
    "country": "Peru",
    "imageUrl": "https://images.unsplash.com/photo-1526392060635-9d6019884377",
    "description": "Historic Incan citadel set high in the Andes Mountains.",
  },
  {
    "id": 9,
    "name": "Sydney Opera House",
    "city": "Sydney",
    "country": "Australia",
    "imageUrl": "https://images.unsplash.com/photo-1506973035872-a4ec16b8d1fb",
    "description": "World-famous performing arts center near Sydney Harbour.",
  },
  {
    "id": 10,
    "name": "Mount Fuji",
    "city": "Tokyo",
    "country": "Japan",
    "imageUrl": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
    "description": "Japan's tallest mountain and a sacred cultural symbol.",
  },
  {
    "id": 11,
    "name": "Niagara Falls",
    "city": "Ontario",
    "country": "Canada",
    "imageUrl": "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    "description": "Massive waterfalls shared by the USA and Canada.",
  },
  {
    "id": 12,
    "name": "Petra",
    "city": "Ma'an",
    "country": "Jordan",
    "imageUrl": "https://images.unsplash.com/photo-1579606032821-4e6161c81bd3",
    "description":
        "Historic archaeological city carved into rose-colored rock.",
  },
  {
    "id": 13,
    "name": "Big Ben",
    "city": "London",
    "country": "United Kingdom",
    "imageUrl": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad",
    "description":
        "Famous clock tower located beside the Houses of Parliament.",
  },
  {
    "id": 14,
    "name": "Pyramids of Giza",
    "city": "Giza",
    "country": "Egypt",
    "imageUrl": "https://images.unsplash.com/photo-1572252009286-268acec5ca0a",
    "description":
        "Ancient pyramids and one of the Seven Wonders of the Ancient World.",
  },
  {
    "id": 15,
    "name": "Blue Mosque",
    "city": "Istanbul",
    "country": "Turkey",
    "imageUrl": "https://images.unsplash.com/photo-1527838832700-5059252407fa",
    "description": "Historic mosque famous for its blue interior tiles.",
  },
  {
    "id": 16,
    "name": "Bali Beach",
    "city": "Bali",
    "country": "Indonesia",
    "imageUrl": "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1",
    "description": "Tropical paradise known for beaches and vibrant culture.",
  },
  {
    "id": 17,
    "name": "Swiss Alps",
    "city": "Zermatt",
    "country": "Switzerland",
    "imageUrl": "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    "description": "Snow-covered mountain ranges and scenic landscapes.",
  },
  {
    "id": 18,
    "name": "Golden Gate Bridge",
    "city": "San Francisco",
    "country": "USA",
    "imageUrl": "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    "description": "Iconic suspension bridge connecting San Francisco Bay.",
  },
  {
    "id": 19,
    "name": "Cappadocia",
    "city": "Nevşehir",
    "country": "Turkey",
    "imageUrl": "https://images.unsplash.com/photo-1641128322548-4db402e0d3f6",
    "description": "Famous for hot air balloons and unique rock formations.",
  },
  {
    "id": 20,
    "name": "Maldives Beach",
    "city": "Malé",
    "country": "Maldives",
    "imageUrl": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8",
    "description": "Crystal-clear waters and luxurious tropical resorts.",
  },
];
